
// n: name, s: sex, m: mother, f: father, ux: wife, vir: husband},

export const familyData = [
  { key: 0, n: 'Aaron', s: 'M', m: -10, f: -11, ux: 1},
  { key: 1, n: 'Alice', s: 'F', m: -12, f: -13},
  { key: 2, n: 'Bob', s: 'M', m: 1, f: 0, ux: 3},
  { key: 3, n: 'Barbara', s: 'F'},
  { key: 4, n: 'Bill', s: 'M', m: 1, f: 0, ux: 5},
  { key: 5, n: 'Brooke', s: 'F'},
  { key: 6, n: 'Claire', s: 'F', m: 1, f: 0},
  { key: 7, n: 'Carol', s: 'F', m: 1, f: 0},
  { key: 8, n: 'Chloe', s: 'F', m: 1, f: 0, vir: 9},
  { key: 9, n: 'Chris', s: 'M'},
  { key: 10, n: 'Ellie', s: 'F', m: 3, f: 2},
  { key: 11, n: 'Dan', s: 'M', m: 3, f: 2},
  { key: 12, n: 'Elizabeth', s: 'F', vir: 13},
  { key: 13, n: 'David', s: 'M', m: 5, f: 4},
  { key: 14, n: 'Emma', s: 'F', m: 5, f: 4},
  { key: 15, n: 'Evan', s: 'M', m: 8, f: 9},
  { key: 16, n: 'Ethan', s: 'M', m: 8, f: 9},
  { key: 17, n: 'Eve', s: 'F', vir: 16},
  { key: 18, n: 'Emily', s: 'F', m: 8, f: 9 },
  { key: 19, n: 'Fred', s: 'M', m: 17, f: 16},
  { key: 20, n: 'Faith', s: 'F', m: 17, f: 16},
  { key: 21, n: 'Felicia', s: 'F', m: 12, f: 13},
  { key: 22, n: 'Frank', s: 'M', m: 12, f: 13},

  { key: -10, n: 'Paternal Grandfather', s: 'M', m: -33, f: -32, ux: -11},
  { key: -11, n: 'Paternal Grandmother', s: 'F'},
  { key: -32, n: 'Paternal Great', s: 'M', ux: -33},
  { key: -33, n: 'Paternal Great', s: 'F'},
  { key: -40, n: 'Great Uncle', s: 'M', m: -33, f: -32},
  { key: -41, n: 'Great Aunt', s: 'F', m: -33, f: -32},
  { key: -20, n: 'Uncle', s: 'M', m: -11, f: -10},

  { key: -12, n: 'Maternal Grandfather', s: 'M', ux: -13},
  { key: -13, n: 'Maternal Grandmother', s: 'F', m: -31, f: -30},
  { key: -21, n: 'Aunt', s: 'F', m: -13, f: -12},
  { key: -22, n: 'Uncle', s: 'M', ux: -21 },
  { key: -23, n: 'Cousin', s: 'M', m: -21, f: -22 },
  { key: -30, n: 'Maternal Great', s: 'M', ux: -31},
  { key: -31, n: 'Maternal Great', s: 'F', m: -50, f: -51},
  { key: -42, n: 'Great Uncle', s: 'M', m: -30, f: -31},
  { key: -43, n: 'Great Aunt', s: 'F', m: -30, f: -31},
  { key: -50, n: 'Maternal Great Great', s: 'F', vir: -51},
  { key: -51, n: 'Maternal Great Great', s: 'M'},
];